# VARIABLES
# ---------
title: DevBlog
titleRss: "DevBlog"
copyright: "Copyright 2012, Kawn"
githubUrl: "https://github.com/kawn/kawn.github.com"

# FEED
#-------
name: DevBlog
description: DevBlog
url: http://kawn.github.com

# JEKYLL
# ------
pygments: true
paginate: 5
markdown: redcarpet
redcarpet:
    extensions: [
        "hard_wrap"
    ]
