# VARIABLES
# ---------
title: "Kawn's Blog"
titleRss: "Kawn's Blog"
copyright: "Copyright 2012, Kawn"
githubUrl: "https://github.com/kawn/kawn.github.com"

# FEED
#-------
name: Kawn's Blog
description: Kawn's Blog
url: http://kawn.github.com

# JEKYLL
# ------
pygments: true
paginate: 5
markdown: redcarpet
redcarpet:
    extensions: [
        "hard_wrap"
    ]
description: "Kawn Blog, a personal page with his current open source projects"
keywords: 
	- Game
	- GameDeveloper
	- Developer
