# VARIABLES
# ---------
title: DevBlog
titleRss: "DevBlog"
copyright: "Copyright 2012, Kawn"
githubUrl: "https://github.com/kawn/kawn.github.com"

# JEKYLL
# ------
pygments: true
paginate: 2
markdown: redcarpet
redcarpet:
    extensions: [
        "hard_wrap",
        "no_intra_emphasis",
        "autolink",
        "fenced_code_blocks",
        "strikethrough",
        "lax_html_blocks",
        "with_toc_data"
    ]
